connection: &connection
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  password: 1234

development:
  <<: *connection
  database: BackEnd_development

test:
  <<: *connection
  database: BackEnd_test

production:
  <<: *connection
  database: BackEnd_production
