connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
<<<<<<< HEAD
  password: abcd1234
=======
  password: 1234
>>>>>>> Ultima_Iteracion

development:
  <<: *connection
  database: BackEnd_development

test:
  <<: *connection
  database: BackEnd_test

production:
  <<: *connection
  database: BackEnd_production
